FROM node:20-bookworm-slim

WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends default-mysql-client ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .

RUN npx prisma generate

RUN chmod +x scripts/prod/entrypoint.sh

ENV NODE_ENV=production
EXPOSE 3000

CMD ["./scripts/prod/entrypoint.sh"]
